### ISSUE TITLE
oppo手机右下角角标

### ISSUE THREAD

**Issue by AnserBaby** [scauzhangpeng/Shortcut#1]
请问oppo手机右下角会有一个角标，该怎么去掉呢？

**Comment by weigecode** [comment]
兄弟，我现在也遇到了，你后面怎么解决的呢？

**Comment by AnserBaby** [comment]
> 兄弟，我现在也遇到了，你后面怎么解决的呢？

没解决

**Comment by weigecode** [comment]
你做的效果其他手机也有角标吗？

**Comment by aLLLiyyy** [comment]
> > 兄弟，我现在也遇到了，你后面怎么解决的呢？
> 
> 没解决

兄弟们，你们都怎么解决了呀

**Comment by aLLLiyyy** [comment]
> 请问oppo手机右下角会有一个角标，该怎么去掉呢？

怎么解决了呀
