### ISSUE TITLE
vivo 检查权限是否开启时，崩溃

### ISSUE THREAD

**Issue by hardlove** [scauzhangpeng/Shortcut#2]
在VIVO手机调用ShortcutPermission.check(Context contenx)检查桌面快捷权限时，crash

测试机型：
vivo Z3 

crash日志如下：
    // java.lang.SecurityException: Permission Denial: opening provider com.bbk.launcher2.data.LauncherProvider from ProcessRecord{f8f30af 16137:com.qiutinghe.change/u0a172} (pid=16137, uid=10172)requires com.bbk.launcher2.permission.READ_SETTINGS or com.bbk.l

**Comment by weigecode** [comment]
兄弟你的改了没，我oppor11也是这样，多打开几次就会崩溃，闪退

**Comment by hardlove** [comment]
> 兄弟你的改了没，我oppor11也是这样，多打开几次就会崩溃，闪退
简单的 try/catch 下
@PermissionResult
    public static int check(Context context) {
        Logger.get().log(TAG, "manufacturer = " + MARK + ", api level= " + Build.VERSION.SDK_INT);
        int result = PERMISSION_UNKNOWN;
        try {
            if (MARK.contains("huawei")) {
                result = checkOnEMUI(context);
            } else if (MARK.contains("xiaomi")) {
                result = checkOnMIUI(context);
            } else if (MARK.contains("oppo")) {
                result = checkOnOPPO(context);
            } else if (MARK.contains("vivo")) {
                result = checkOnVIVO(context);
            } else if (MARK.contains("samsung") || MARK.contains("meizu")) {
                result = PERMISSION_GRANTED;
            }
        } catch (Exception e) {
            //修复vivo Z3 检测权限时crash问题
            // java.lang.SecurityException: Permission Denial: opening provider com.bbk.launcher2.data.LauncherProvider from ProcessRecord{f8f30af 16137:com.qiutinghe.change/u0a172} (pid=16137, uid=10172)
            // requires com.bbk.launcher2.permission.READ_SETTINGS or com.bbk.l
            e.printStackTrace();
        }
        return result;
    }

**Comment by weigecode** [comment]
好的，多谢，请问你也是做桌面快捷方式功能吗？这个demo生成的快捷方式是不是右下角有个自己的应用图标？你有遇到吗？是否有方案解决呢？如果有方案，请指教一下，感谢（抱拳）！

**Comment by hardlove** [comment]
去角标，我也没有找到什么方案呢。市面上有些应用是去掉了角标的，不知道他们是如何做到的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午2:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [scauzhangpeng/Shortcut] vivo 检查权限是否开启时，崩溃 (#2)





 
好的，多谢，请问你也是做桌面快捷方式功能吗？这个demo生成的快捷方式是不是右下角有个自己的应用图标？你有遇到吗？是否有方案解决呢？如果有方案，请指教一下，感谢（抱拳）！

**Comment by weigecode** [comment]
是的，应用市场上有产品是去了的，不知如何实现，最近公司也在做这个功能，然后角标一直没找到方案去掉

**Comment by hardlove** [comment]
你们产品上架了吗？另外我发现这个库权限检查有的设备并不可靠



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午2:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [scauzhangpeng/Shortcut] vivo 检查权限是否开启时，崩溃 (#2)





 
是的，应用市场上有产品是去了的，不知如何实现，最近公司也在做这个功能，然后角标一直没找到方案去掉

**Comment by weigecode** [comment]
还没有上，最近才开始做，权限检查应该是不全，毕竟安卓机型太多了

**Comment by Yumore** [comment]
com.bbk.launcher2.data.provider.LauncherProvider 将authority换成这个就好了

**Comment by ShowMeThe** [comment]
有没有人有解决方案 这个在vivo部分机型上都存在

**Comment by a2025140672** [comment]
> 有没有人有解决方案 这个在vivo部分机型上都存在

vivo通过contentResolver读取系统文件报错堆栈：
java.lang.SecurityException: Permission Denial: opening provider com.bbk.launcher2.data.LauncherProvider from ProcessRecord{f8f30af 16137:com.qiutinghe.change/u0a172} (pid=16137, uid=10172)requires com.bbk.launcher2.permission.READ_SETTINGS or com.bbk.launcher2.permission.WRITE_SETTINGS

说明没有定义这两个配置：
com.bbk.launcher2.permission.READ_SETTINGS
com.bbk.launcher2.permission.WRITE_SETTINGS

需要在AndroidManifest.xml里面加上这两句，我试了可以读取到权限了。

**Comment by a2025140672** [comment]
> 有没有人有解决方案 这个在vivo部分机型上都存在

说明没有定义这两个配置：
com.bbk.launcher2.permission.READ_SETTINGS
com.bbk.launcher2.permission.WRITE_SETTINGS

需要在AndroidManifest.xml里面加上这两句uses-permission，我试了可以读取到权限了。
