### ISSUE TITLE
华为P30检测权限失败

### ISSUE THREAD

**Issue by cizkey** [scauzhangpeng/Shortcut#3]
在华为P30手机logout报：
NoSuchMethodException: com.huawei.hsm.permission.PermissionManager.canSendBroadcast 

应该是检测的方式修改了，不再使用PermissionManager#canSendBroadcast来。

我看了：http://www.lefo.me/2017/05/19/shortcut-permission/ 这篇文章，感觉华为这个还是巨坑一个。

**Comment by luhongalex** [comment]
有解决这个问题吗？
